import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import AddMovieForm from "../components/Form/AddMovieForm";
import MovieNightHeader from "../components/MovieNightHeader";

const SuggestMovieView = () => (
  <>
    <Head>
      <title>Login • SuggestAndVote</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Flex px={6} pb={6} flexDir="column" overscrollY={"none"}>
      <MovieNightHeader />
      <AddMovieForm />
    </Flex>
  </>
);

export default SuggestMovieView;
