import { Button, Flex } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import MovieCard from "../components/MovieCard";
import { testMovieCardData } from "../components/MovieCard/testData";
import MovieNightHeader from "../components/MovieNightHeader";
import { PlusIcon } from "../icons";

const VoteView = () => (
  <>
    <Head>
      <title>Movie List • SuggestAndVote</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Flex px={6} pb={6} flexDir="column">
      <MovieNightHeader />
      <Flex id="movie-container" flexDir="column" gap={4} pt={6} pb={20}>
        {testMovieCardData.map((movie, index) => (
          <MovieCard
            movie={movie}
            voteFor={index + 2}
            voteAgainst={index}
            key={movie.imdbUrl + movie.runtime}
          />
        ))}
      </Flex>
    </Flex>
    <Flex w="100vw" justify="center" pos="fixed" bottom={0} p={6}>
      <Link href="/suggest">
        <Button
          size="lg"
          colorScheme="purple"
          leftIcon={<PlusIcon fill={"transparent"} />}
        >
          Sugest new movie
        </Button>
      </Link>
    </Flex>
  </>
);

export default VoteView;
